/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sudoku;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Sudoku classUnderTest = new Sudoku();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
